import { JetBrains_Mono } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import StarsCanvas from "./components/ui/Stars";

const jetBrainsMono = JetBrains_Mono({
  variable: "--font-jetBrainsMono",
  subsets: ["latin"],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800']
});

export const metadata = {
  title: "João's Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${jetBrainsMono.variable} antialiased`}
      >
        <StarsCanvas />
        <Header />
        {children}
      </body>
    </html>
  );
}
